steps:
    run:
        image: codeberg.org/sentryshot/sentryshot-ci:v0.2.0
        commands: "nix-shell /shell.nix --command 'npm install && ./misc/utils.sh ci'"
        when:
            event: [push, pull_request]

    build-x86_64:
        image: codeberg.org/sentryshot/sentryshot-build-x86_64:v0.2.0
        commands: "nix-shell /shell.nix --command './misc/utils.sh build-target x86_64'"
        when:
            event: [tag]
    build-aarch64:
        image: codeberg.org/sentryshot/sentryshot-build-aarch64:v0.2.0
        commands: |
            # Prebuilt library because I couldn't get it to cross-compile.
            tflite="./misc/nix/aarch64-tflite/out/libtensorflowlite_c.so"
            curl https://codeberg.org/api/packages/SentryShot/generic/tflite/0.0.1/libtensorflowlite_c.so -o "$tflite"
            if ! printf "8f9acc6e4cace0f541ee4cd41fe553b0aa66a0a37be3ffde23224ca37c720067 %s" "$tflite" | sha256sum -c; then
                printf "invalid aarch64 tflite checksum\n"
                exit 1
            fi

            nix-shell /shell.nix --command './misc/utils.sh build-target-aarch64'
        when:
            event: [tag]

    tarball:
        image: busybox:1.36
        commands: |
            tag="${CI_COMMIT_TAG}"
            tar -czvf "./build/sentryshot-$tag-x86_64.tar.gz" -C "./build/x86_64" .
            tar -czvf "./build/sentryshot-$tag-aarch64.tar.gz" -C "./build/aarch64" .
            ls ./build

            awk '/^## / { if (p) { exit }; if ($2 == "`${CI_COMMIT_TAG}`") { p=1; next } } p && NF' "./misc/CHANGELOG.md" > release-notes.txt
            cat ./release-notes.txt

            ./misc/utils.sh download-debian-libusb
        when:
            event: [tag]

    docker:
        image: woodpeckerci/plugin-docker-buildx
        settings:
            platforms: linux/amd64,linux/arm64
            repo: codeberg.org/sentryshot/sentryshot
            registry: codeberg.org
            dockerfile: "./misc/Dockerfile"
            tags: ["${CI_COMMIT_TAG}", "latest"]
            username: "Curid"
            password:
                from_secret: cb_token
        when:
            event: [tag]

    release:
        image: woodpeckerci/plugin-gitea-release
        settings:
            base_url: https://codeberg.org
            files:
                - "./build/sentryshot-v*"
            api_key:
                from_secret: cb_token
            target: main
            note: "./release-notes.txt"
            title: "release ${CI_COMMIT_TAG}"
        when:
            event: [tag]
