[package]
name = "vod"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
name = "vod"
path = "vod.rs"
doctest = false

[dependencies]
common.path = "../common"
mp4.path = "../mp4"
recdb.path = "../recdb"
recording.path = "../recording"

bytesize.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
pin-project.workspace = true


[dev-dependencies]
pretty_assertions.workspace = true
pretty-hex.workspace = true
test-case.workspace = true
tempfile.workspace = true
